# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - ./src/lib/graphql/schema.graphql
      # - ./src/**/*.graphql
      - ./$houdini/graphql/schema.graphql
    documents:
      - ./src/**/*.gql
      - ./$houdini/graphql/documents.gql
