# Typical File for extension: vscode-graphql & CodeGen!
projects:
  default:
    schema:
      - ./src/**/*.graphql
      - ./$houdini/graphql/schema.gql
    documents:
      - ./src/**/*.gql
      - ./$houdini/graphql/documents.gql
