query BurstinessDiscussions($querystring: String!, $endCursor: String = null) {
	rateLimit {
		cost
		limit
	}
	search(query: $querystring, type: DISCUSSION, first: 100, after: $endCursor) @paginate {
		edges {
			node {
				__typename
				... on Discussion {
					url
					createdAt
				}
			}
		}
	}
}
