query BurstinessIssues($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		issues(
			first: 100
			orderBy: { field: CREATED_AT, direction: ASC }
			filterBy: { since: "2022-06-07T00:00:00" }
		) {
			edges {
				node {
					title
					createdAt
					closedAt
					publishedAt
					resourcePath
					url
				}
			}
			totalCount
			pageInfo {
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
			}
		}
	}
}
