query BurstinessIssues($owner: String!, $name: String!, $date: DateTime!) {
	repository(owner: $owner, name: $name) {
		issues(first: 100, orderBy: { field: CREATED_AT, direction: ASC }, filterBy: { since: $date }) {
			edges {
				node {
					title
					createdAt
					closedAt
					publishedAt
					resourcePath
					url
				}
			}
			totalCount
			pageInfo {
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
			}
		}
	}
}
