query BurstinessDiscussions($querystring: String!) {
	rateLimit {
		cost
		limit
	}
	search(query: $querystring, type: DISCUSSION, first: 100) @paginate {
		edges {
			node {
				__typename
				... on Discussion {
					url
					createdAt
				}
			}
		}
	}
}
