query Languages($name: String!, $owner: String!) {
	repository(name: $name, owner: $owner) {
		languages(first: 100) {
			totalSize
			edges {
				size
				node {
					name
					color
				}
			}
		}
	}
}
