query Collaborators(
	$name: String!
	$owner: String!
	$affiliation: CollaboratorAffiliation!
	$withName: Boolean! = false
) {
	repository(name: $name, owner: $owner) {
		collaborators(first: 100, affiliation: $affiliation) {
			nodes {
				# login is only included when $withName is true
				login @include(if: $withName)
				name
				location
			}
		}
	}
}
