query Collaborators($name: String!, $owner: String!) {
	repository(name: $name, owner: $owner) {
		collaborators(first: 100, affiliation: ALL) @paginate {
			edges {
				node {
					# login is only included when $withName is true
					# login @include(if: $withName)
					location
				}
			}
		}
	}
}
