query Burstiness($owner: String!, $name: String!) {
	repository(owner: $owner, name: $name) {
		issues(
			first: 100
			orderBy: { field: CREATED_AT, direction: ASC }
			filterBy: { since: "2022-06-07T00:00:00" }
		) {
			edges {
				node {
					title
					createdAt
					closedAt
					publishedAt
					resourcePath
				}
			}
			totalCount
			pageInfo {
				endCursor
				startCursor
				hasNextPage
				hasPreviousPage
			}
		}
		pullRequests(first: 100, orderBy: { field: CREATED_AT, direction: ASC }) {
			edges {
				node {
					createdAt
					closedAt
				}
			}
		}
		commitComments(first: 100) {
			edges {
				node {
					body
					author {
						login
					}
					publishedAt
					resourcePath
				}
			}
		}
		discussions(first: 100) {
			edges {
				node {
					publishedAt
					reactions {
						edges {
							node {
								content
							}
						}
					}
				}
			}
		}
	}
}
